name: resena
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  mongo_dart: ^0.8.2
  dotenv: ^4.1.0
  async: ^2.2.0
  grpc: ^3.1.0
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
